### ISSUE TITLE
Application crashes in artist info screen

### ISSUE THREAD

**Issue by venkateshshukla** [venkateshshukla/musicbrainz-android#2]
Search for an artist. Chose among the list. Wait for a second. Bamm... the application crashes.

**Comment by venkateshshukla** [comment]
Following are the logs of the logcat after the crash

```
03-29 06:33:57.642    1726-1829/org.musicbrainz.mobile E/AndroidRuntime﹕ FATAL EXCEPTION: ModernAsyncTask #3
    Process: org.musicbrainz.mobile, PID: 1726
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.ArrayList org.musicbrainz.mobile.async.external.result.LastFmArtist.image' on a null object reference
            at org.musicbrainz.mobile.async.external.ArtistBioLoader.loadInBackground(ArtistBioLoader.java:29)
            at org.musicbrainz.mobile.async.external.ArtistBioLoader.loadInBackground(ArtistBioLoader.java:12)
            at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
            at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by venkateshshukla** [comment]
Interestingly, the application has no logging whatsoever.
